import streamlit as st
import google.generativeai as palm
import os

# Configure the generative AI API key
palm.configure(api_key="AIzaSyDiH8y9OcFbC6v_MTkuEBKX5ezaW8cFNeY")

generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 2048,
}

model = palm.GenerativeModel(model_name="gemini-pro",
                              generation_config=generation_config)

def initiate(user_input):
    prompt = """
    Analyzing the following text, determine whether it was generated by a human or artificial intelligence. 
    Provide the output as only 'Generated by Human' or 'Generated by AI' without your reasoning. Give the percentages too.
    Don't explain why the text was detected as human-made or AI-generated, just show a brief output of who it was created by.
    Remember, do not give an explanation about the text. 
    """ + "text =",user_input
    response = model.generate_content(prompt)
    print("ai response =", response.text)
    return response.text

def main():
    # Set a background image
    st.markdown(
        """
        <style>
            .stApp {
                background-image: url('');
                background-size: cover;
                background-repeat: no-repeat;
                height: 100vh;
            }
            .blur-overlay {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(255, 255, 255, 65);  /* Adjust alpha channel for transparency */
                z-index: 1;
            }
            .title {
                color: #c76f38; /* Ubah kode warna sesuai kebutuhan */
            }
        </style>
        """,
        unsafe_allow_html=True
    )

    st.title("AI Text Detection App")
    st.subheader("Was this text written by a human👨‍💼 or AI🤖?")
    st.sidebar.title("Info")

    user_input = st.text_area("Paste your text below: (Max 2048)")

    if st.button("Analyze"):
        if user_input:
            result = initiate(user_input)
            st.success(f"AI Response: {result}")
        else:
            st.warning("Please enter text for analysis.")

    # Decorations and styling
    st.sidebar.markdown("### This app was made by :")
    st.sidebar.info("Deva Putra Setya Pratama")
    st.sidebar.info("Niko Silabest")

if __name__ == "__main__":
    main()